version: '3'

services:
  postgres-perso:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=value
    ports:
      - '5432:5432'
    volumes:
      - ./dbs:/var/lib/postgresql/data

volumes:
  dbs:
    driver: local